### ISSUE TITLE
Long gearsets gain undesirable horizontal scrollbars

### ISSUE THREAD

**Issue by moxian** [xiv-gear-planner/gear-planner#115]
1. open a gearset with many sets in it. E.g. https://xivgear.app/#/sl/01890444-a3ba-4004-89c3-a743c8af0f75
2. either click on any of the sets or shrink your browser window height until it can't fit all of the sets on the page
3. see the list gain a vertical scrollbar (reasonable), which in turn makes it also gain a horizontal scrollbar (unreasonable) and look overall jank. See screenshot.
![20240525-230716-firefox](https://github.com/xiv-gear-planner/gear-planner/assets/7831163/80e82942-3d66-467f-a096-2d1c7d8f9c0c)

**Comment by xpdota** [comment]
Can you check if this is fixed now? It seems to not be doing it anymore.

It might still be worth it to me to add a scroll gutter so that the table doesn't change width when the scrollbar appears or disappears.

**Comment by moxian** [comment]
Still happening to me.
I'm using Firefox, if this matters
