### ISSUE TITLE
feature: Ability to undo or disable auto-save

### ISSUE THREAD

**Issue by Makar8000** [xiv-gear-planner/gear-planner#154]
It would be nice if there was a way to undo. I just realized everything auto-saves, so no undo feature is potentially damaging since misclicking is a thing and you can't F5 to reset all changes. It can be difficult to figure out what gear piece changed and also figure out what materia used to be slotted.

If undo is not feasible in the current design then at least some way to toggle the auto-save feature off.

**Comment by xpdota** [comment]
Undo implementation idea: whenever a stats recompute is triggered, push the new state to some kind of undo history.
