### ISSUE TITLE
Relic shield-can't edit substats

### ISSUE THREAD

**Issue by Kadomony** [xiv-gear-planner/gear-planner#18]
It looks like the program allows you to put in custom substats on the relic weapons, but the shield seems fixed at zeroes.

**Comment by xpdota** [comment]
I think I fixed it - can you give it a try on [beta.xivgear.app](https://beta.xivgear.app/#/)?

**Comment by Kadomony** [comment]
Looks like it works on the beta site.

**Comment by xpdota** [comment]
Thanks for testing!
