### ISSUE TITLE
Autoattack delay handling

### ISSUE THREAD

**Issue by amakiirs** [xiv-gear-planner/gear-planner#183]
Currently (as best I can tell, anyway), autoattacks are treated as having the stated potency, like any other damaging action.

Autoattacks, in general, average this potency per 3 seconds, but actually apply every [autoattack delay] seconds for (base / 3 * delay) potency per hit, rather than hitting for base potency every 3 seconds. While these are equivalent on average, this makes any calculations involving autos in buffs inaccurate, and it also makes it easy to get auto damage wrong (e.g., by calculating the number of autos based on the actual auto delay, but not adjusting the potency per hit accordingly).

Probably the best solution is to expose the `aaDelay` or `weaponDelay` (I'm not entirely clear on what the difference between the two is?) to usage-sim-creators for use in deciding how many autos should be used in a given time period, adjust the damage done by autos on the backend (i.e., in the processor `count_sim.ts`), and clearly document that this happens.

Cycle-based sims appear to correctly use auto delay to decide the time between autos, but I don't see any adjustment of potency to account for the delay in, e.g.,
https://github.com/xiv-gear-planner/gear-planner/blob/f27b7dbdb2286515d6db1f8ec2f4cd7c6171ebe9/packages/core/src/sims/cycle_sim.ts#L896

**Comment by nikroulah** [comment]
The potency adjustment is there, it's hidden away somewhere and the cyclesim rotation preview table doesn't adjust the potency in the UX -- I agree that the displayed number should have an asterisk and/or show the adjusted potency rather than the amortized per 3s potency
