### ISSUE TITLE
Allow changing level of a sheet

### ISSUE THREAD

**Issue by teatwig** [xiv-gear-planner/gear-planner#185]
I started updating the gear in my old lvl 90 sheet as I got new pieces, only to realize I can't select the new materia since it's still capped at level 90.
Currently this would mean recreating the whole sheet ~~or editing the exported JSON but that's not the best user experience~~.

In general it would be nice if you could change all the options you select when creating a new sheet

- job (as long as it uses the same type of gear?)
- level
- item level sync

**Comment by xpdota** [comment]
I want to allow sheet properties to be changed via "Save As" rather than just the name.

In the meantime, you can create a new sheet manually, but then export/import the new sheet into the new sheet.
