### ISSUE TITLE
Default materia option

### ISSUE THREAD

**Issue by qaphla** [xiv-gear-planner/gear-planner#2]
A generally useful feature would be the option to set a default materia priority that the user wishes to work with, and automatically populate the materia slots of newly selected gear according to this priority, meaning that only materia that deviate from standard priority would need to be manually entered.

**Comment by xpdota** [comment]
This works now 
![image](https://github.com/xiv-gear-planner/gear-planner/assets/14287379/a77bfd93-6b93-43fd-ad06-d299ede5f7ce)
