### ISSUE TITLE
Enhancement: Caveat for damage/100p

### ISSUE THREAD

**Issue by amakiirs** [xiv-gear-planner/gear-planner#203]
It is not currently obvious to casual users of the tool that the damage/100p sim doesn't reflect skill speed and should not be used to compare directly across speeds.

It would be helpful to have some sort of warning (Krom suggests an exclamation mark with a modal, or a note on the set viewer) making this clear.

It might also be further useful to allow for similar caveat notes to be marked on other sims, especially if the functionality to implement it is uniform across all sims.

**Comment by xpdota** [comment]
This was fixed in #226
