### ISSUE TITLE
Integration with Teamcraft

### ISSUE THREAD

**Issue by pastUser** [xiv-gear-planner/gear-planner#249]
Teamcraft has an API where you can send gear and materia and have it produce a crafting list for you.

It would be great if you could integrate with them. 

The API is detailed here

https://wiki.ffxivteamcraft.com/dev-stuff/import-a-list-from-another-tool

**Comment by xpdota** [comment]
I have this on [https://atest.xivgear.app/](https://atest.xivgear.app/), can you try it out?

![image](https://github.com/user-attachments/assets/d5d633d2-a8eb-4727-a62d-4bfc65f54850)

**Comment by pastUser** [comment]
Thanks so much!
