### ISSUE TITLE
feature: Save Materia selection on a previously selected item and re-apply it when switching back

### ISSUE THREAD

**Issue by Makar8000** [xiv-gear-planner/gear-planner#254]
Might be a duplicate of #27 but not sure since there is no description.

This feature is mostly because #154 is not implemented yet, but I think this has some use case even after undo is added.

Basically, if I select Item A and add Crit Materia, then I switch to Item B, then back to A, I would like it to restore the Materia configuration that was there prior to switching to Item B.

Materia slotting for crafted pieces can be very specific, and it is not easy to remember what exactly you had slotted. If I accidently select a non-crafted piece for a slot and then go back to the crafted piece, I have to re-add the Materia which I may not even remember.

**Comment by xpdota** [comment]
For this one, I'm thinking I'll just change "fill newly selected items" checkbox into a dropdown with:
- Empty (current behavior with that option disabled)
- Auto-fill (current behavior with that option enabled)
- Keep current (tries to keep current materia, even if it doesn't make sense)
- Select last (remember per-item)
