### ISSUE TITLE
Feature: Change iLvl sync/Item floor after creating a sheet

### ISSUE THREAD

**Issue by RhyTamok** [xiv-gear-planner/gear-planner#260]
It would be nice to be able to adjust the sync level and floor level of a sheet afterwards. When you make a mistake and only notice it after creating multiple sets you have to make a completely new sheet. 
An option to adjust these could be added to the "more actions" menu.

**Comment by xpdota** [comment]
You can sort of do this by using "Save As" and changing the level, ilvl, or other properties of the sheet. Does that work well enough?

**Comment by RhyTamok** [comment]
This is a viable solution for me (now that I know it) but I don't think it's clear for the average user. It's not a super important issue so I can definitely understand leaving it as is. 
May I suggest explaining the floor level somewhere though? I had multiple friends confused by it because the level you select makes it seem like it would be the cap and not a floor.

**Comment by xpdota** [comment]
With the new data manager, there is no longer a min/max per-sheet. It's now a global minimum of i290.
