### ISSUE TITLE
Bug: Sim DPS should be calculated with specified kill time

### ISSUE THREAD

**Issue by DiaStarvy** [xiv-gear-planner/gear-planner#282]
The sim DPS numbers are currently calculated using 
final DPS = total damage / [prepull time + start time of last GCD].

Since the last GCD is pro-rated based on the specified kill time it would be more accurate and less sensitive to small kill time differences to use
final DPS = total damage / specified kill time.

Prepull time should arguably be excluded as it would more fairly compare different prepull behaviour such as Pneuma vs Toxikon opener. It would also be more in line to how fflogs calculates DPS as well as how much DPS you would contribute in an opening phase or a full enrage pull.

**Comment by xpdota** [comment]
I have a fix for this. Pre-pull time was never included, that doesn't seem to be correct.
