### ISSUE TITLE
Bug: level/item level sync does not work properly in certain circumstances

### ISSUE THREAD

**Issue by xiashtra** [xiv-gear-planner/gear-planner#317]
FFXIV considers both the level and item level of the item when syncing gear.  For example, using lvl 94, ilvl 663 gear fully pentamelded, and then syncing to lvl 90, ilvl 665, all materia melds on the gear will be ignored, since it is being synced from lvl 94 -> lvl 90, even though ilvl 663 is below the maximum of ilvl 665 possible at lvl 90.  This is primarily relevant to creating gearsets for Criterion, as both AMR and AAI are force synced to lvl 90, ilvl 665.

Xivgear currently only considers item level when syncing, which leads to including materia on gear that the game would ignore.

Example set: https://xivgear.app/?page=sl%7Cca769fdb-0f40-4a78-943f-f4b3b7228dc5 All materia *should* be ignored here, as it is syncing lvl 94 gear to lvl 90.

**Comment by xpdota** [comment]
One thing I can't seem to figure out from the data alone is - why does 94/663 get synced to 660, but 100 gets synced to 665? Is it just because 663 is already less than 665, so it forces it down to 660?

**Comment by xiashtra** [comment]
> One thing I can't seem to figure out from the data alone is - why does 94/663 get synced to 660, but 100 gets synced to 665? Is it just because 663 is already less than 665, so it forces it down to 660?

Best guess?  Probably something like that. There's nothing else between 660 and 665, so it's really just that one set that might cause an issue.

**Comment by xiashtra** [comment]
I'm going to try and get a hold of the 91/92/93 leveling gear and make sure there's no other surprises.

**Comment by xpdota** [comment]
Would be interesting to see what happens with a level 90 item (Riversbreath set) since it's lvl 91 i650, and 650 is lower than both 660 and 665.
