### ISSUE TITLE
Sync gear based on both lvl and ilvl

### ISSUE THREAD

**Issue by jtcasper** [xiv-gear-planner/gear-planner#359]
Related to questions regarding aloalo gearsets (the only place in game this is important currently), gear syncs _by level_ to remove materia slots, but gear below the ilvl cap retains its ilvl / stats:

basically, when ilvl is synced to 665 like in [this set](https://xivgear.app/?page=sl%7C5c87c40b-9263-4a11-ae1c-7b193db6b9d6) the Zormor Tachi should lose its meld slots

![image](https://github.com/user-attachments/assets/27e3adce-1643-44d1-995e-678f50bf8687)

just like the 663 cobalt tungsten blade does:
![image](https://github.com/user-attachments/assets/fdbc7940-6e71-47ec-a298-ade965e8d402)

https://github.com/xiv-gear-planner/gear-planner/blob/d579a6b2e8ceb56ba70122e158d21b9db764614a/packages/core/src/datamanager_xivapi.ts#L732

**Comment by xpdota** [comment]
Fixed in #360
