### ISSUE TITLE
Bug: Source for unaugmented tome items displays as "Unknown"

### ISSUE THREAD

**Issue by xiashtra** [xiv-gear-planner/gear-planner#381]
![image](https://github.com/user-attachments/assets/9ecfd549-2966-4d46-9c21-88cd99876ae6)

**Comment by xpdota** [comment]
This is probably a "can't fix yet". One of the data points necessary for this is whether a shop exists, and Xivapi currently does not have a good way to do this. 

See https://discord.com/channels/474518001173921794/474519195963490305/1280314788861186059

But I do have a (currently broken) boilmaster instance set up now, so expensive queries might be more viable now.

**Comment by xpdota** [comment]
Come to think of it, is there ever a situation where the name of the augmented version is _not_ just "Augmented" + the name of the un-augmented version? It could work to just match on the name.

**Comment by xiashtra** [comment]
> Come to think of it, is there ever a situation where the name of the augmented version is _not_ just "Augmented" + the name of the un-augmented version? It could work to just match on the name.

Probably nothing we care about, I think there was some ARR equipment that used a different naming scheme, e.g. Weathered [x] => [x] (so the reverse of [x] => Augmented [x] we have today).
