### ISSUE TITLE
Some items are showing too many materia slots

### ISSUE THREAD

**Issue by xpdota** [xiv-gear-planner/gear-planner#89]
![image](https://github.com/xiv-gear-planner/gear-planner/assets/14287379/52a74ab9-e1fc-4a83-8e07-d1fd85a538d1)

https://xivapi.com/Item/34431

> MateriaSlotCount: 2

**Comment by xpdota** [comment]
![image](https://github.com/xiv-gear-planner/gear-planner/assets/14287379/f4fb2bad-4c8f-4b01-9482-820babc97e79)
You can, in fact, overmeld these.

**Comment by xiashtra** [comment]
> "IsAdvancedMeldingPermitted": 1
afaik all overmeldable items have `MateriaSlotCount: 2`
